sonata_admin:
    title: 'Administration'
    dashboard:
        groups:
            app.product:
                label: "Les produits"
                items:
                    - admin.product
            app.category:
                label: "Les éléments liés au produit"
                items:
                    - admin.category
                    - admin.tag
        blocks:
            -
                position: left
                type: sonata.block.service.text
                settings:
                    content: "<h1>Bienvenue sur l'administration</h1>"
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [app.product]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [app.category]

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
        sonata.block.service.text:
